# Regenerates ColdTableProbeModels.g.cs — the 200 distinct entity types TASK-290's cold-table storm needs.
#
# Run from the test project root:  pwsh tools/gen-cold-table-probes.ps1
#
# It exists so the generated file is a derived artefact rather than 200 hand-written lines nobody dares
# touch. The count and the name width are the two things worth changing here:
#
#   -Count : how many distinct cold tables the storm covers. The consumer's reproduction needed ~190
#            (its seed's actual profile); below ~100 the condition has not been seen.
#   width  : names are zero-padded to a FIXED width on purpose. AbstractConnector.CreatedTablesNamedIn
#            decides "is this the anomaly?" by testing whether a recorded table name is a SUBSTRING of the
#            failing statement, so equal-length names make that channel unable to contaminate the result.
#            Do not switch to Probe1/Probe2/... — "Probe1" is a substring of "Probe100".
param([int]$Count = 200)

$out = Join-Path $PSScriptRoot '..\ColdTableProbeModels.g.cs'
$sb = [System.Text.StringBuilder]::new()

[void]$sb.AppendLine(@'
// GENERATED by tools/gen-cold-table-probes.ps1 — do not hand-edit; regenerate instead.
//
// TASK-290 — 200 distinct entity types over ONE database file, for the cold-table storm reproduction.
//
// ⚠ WHY 200 SEPARATE TYPES AND NOT ONE TYPE HIT 200 TIMES. Same-table concurrency serialises on that
// store's own `_initLock` (AbstractAsyncStore.cs), so it reproduces nothing — measured on the consumer
// side, where two earlier hypotheses fired 8 and 12 requests at ONE cold table and found nothing. The
// condition this file exists to create is ~190 distinct `_initLock`s with no serialisation between them,
// one shared connector, one file. A store is generic in its entity type and the framework caches table
// metadata per type, so "distinct cold tables" means distinct CLR types; there is no shorter way to say it.
//
// ⚠ WHY FIXED-WIDTH NAMES. `AbstractConnector.CreatedTablesNamedIn` decides whether an escape is the
// anomaly by testing whether a recorded table name is a SUBSTRING of the statement. Every name here is
// exactly 8 characters, so no name can be a proper substring of another and that channel cannot
// contaminate the measurement. The colliding case is measured deliberately and separately.
// A .g.cs name puts the compiler in auto-generated mode, where a nullable annotation without an
// explicit directive is CS8669. The project builds warning-free (CLAUDE.md § Code Style), so say it.
#nullable enable

using Birko.Data.Models;
using Birko.Data.SQL.Attributes;

namespace Birko.Data.SQL.SqLite.Tests;
'@)

for ($i = 0; $i -lt $Count; $i++) {
    $n = $i.ToString('000')
    [void]$sb.AppendLine("[Table(`"Probe$n`")] public class Probe$n : AbstractDatabaseModel { public string? Value { get; set; } }")
}

[void]$sb.AppendLine('')
[void]$sb.AppendLine('public static class ColdTableProbes')
[void]$sb.AppendLine('{')
[void]$sb.AppendLine('    /// <summary>The 200 probe types, in declaration order.</summary>')
[void]$sb.AppendLine('    public static readonly System.Type[] All = new System.Type[]')
[void]$sb.AppendLine('    {')
for ($i = 0; $i -lt $Count; $i++) {
    $n = $i.ToString('000')
    [void]$sb.AppendLine("        typeof(Probe$n),")
}
[void]$sb.AppendLine('    };')
[void]$sb.AppendLine('}')

[System.IO.File]::WriteAllText((Resolve-Path -LiteralPath (Split-Path $out) | ForEach-Object { Join-Path $_ (Split-Path $out -Leaf) }), $sb.ToString())
Write-Host "wrote $Count probe types"
