#!/usr/bin/env dotnet
#:project AuditCommon/AuditCommon.csproj

// gen-cold-table-probes — regenerates the cold-table storm's probe types for BOTH SQL suites.
//
// Run:  dotnet run tools/gen-cold-table-probes.cs            (from Birko.Framework/)
//       dotnet run tools/gen-cold-table-probes.cs -- --check  (regenerate to memory; fail if stale)
//
// The generated files exist so they are derived artefacts rather than hundreds of hand-written lines
// nobody dares touch. Two things are worth changing per target, and both live in the profiles below:
//
//   Count : how many distinct cold tables the storm covers. The consumer's reproduction needed ~190
//           (its seed's actual profile); below ~100 the condition has not been seen. PostgreSQL uses
//           fewer on purpose — see its header.
//   Width : names are zero-padded to a FIXED width on purpose. AbstractConnector.CreatedTablesNamedIn
//           decides "is this the anomaly?" by testing whether a recorded table name is a SUBSTRING of
//           the failing statement, so equal-length names make that channel unable to contaminate the
//           result. Do not switch to Probe1/Probe2/... — "Probe1" is a substring of "Probe100".
//
// PORTED FROM PowerShell 2026-09-19 (TASK-477), for the reason in TASK-476: the original was
// `tests/Birko.Data.SQL.SqLite.Tests/tools/gen-cold-table-probes.ps1` and did not run on Linux.
// `Join-Path $PSScriptRoot '..\ColdTableProbeModels.g.cs'` leaves a literal backslash there, so
// `Split-Path -Leaf` returned `..\ColdTableProbeModels.g.cs` and the script wrote a junk file with a
// backslash IN ITS NAME inside tools/, left the real generated file untouched, printed
// "wrote 200 probe types" and exited 0. Reporting success having done nothing is the same family of
// defect as the four audits.
//
// ⚠ AND IT NEVER PRODUCED THE POSTGRESQL FILE. `PgColdTableProbeModels.g.cs` carried the header
// "GENERATED by tools/gen-cold-table-probes.ps1" while that project has no tools/ directory, and the
// committed script hardcoded the SQLite count, prefix, width, namespace, class name and output path —
// it could not have emitted it. So one of the two "generated" files was a hand-maintained copy wearing
// a generated file's warning not to hand-edit it. Both are now genuinely generated from here.
//
// ⚠ WHY THIS LIVES IN Birko.Framework/tools/ AND NOT BESIDE THE SUITE IT FEEDS. The .ps1 sat inside
// `tests/Birko.Data.SQL.SqLite.Tests/tools/`, which is fine for a file the compiler ignores. A `.cs`
// file there would be swept up by that project's default `**/*.cs` glob and compiled into the test
// assembly, where its top-level statements are a second entry point. It cannot live under `tests/`
// at all, either: build-and-test.yml loops `for p in tests/*/` and runs `dotnet test "$p"`, so a
// `tests/tools/` directory would be treated as a test project and fail the job.

using System.Text;
using System.Runtime.CompilerServices;
using AuditCommon;

static string ScriptDirectory([CallerFilePath] string path = "") => Path.GetDirectoryName(path)!;

var checkOnly = args.Contains("--check", StringComparer.OrdinalIgnoreCase)
             || args.Contains("-Check", StringComparer.OrdinalIgnoreCase);

var unknown = args.FirstOrDefault(a => !a.Equals("--check", StringComparison.OrdinalIgnoreCase)
                                    && !a.Equals("-Check", StringComparison.OrdinalIgnoreCase));
if (unknown is not null)
{
    Console.Error.WriteLine($"Unrecognised argument: {unknown}");
    Console.Error.WriteLine("Usage: dotnet run tools/gen-cold-table-probes.cs [-- --check]");
    return 2;
}

// Birko.Framework/tools -> Birko.Framework -> the repo root that holds tests/
var repoRoot = Path.GetFullPath(Path.Combine(ScriptDirectory(), "..", ".."));

var profiles = new Profile[]
{
    new(
        RelativePath: Path.Combine("tests", "Birko.Data.SQL.SqLite.Tests", "ColdTableProbeModels.g.cs"),
        Namespace: "Birko.Data.SQL.SqLite.Tests",
        Prefix: "Probe",
        Width: 3,
        Count: 200,
        ClassName: "ColdTableProbes",
        BlankLineAfterNamespace: false,
        DocComment: "    /// <summary>The {0} probe types, in declaration order.</summary>",
        Header: """
            //
            // TASK-290 — 200 distinct entity types over ONE database file, for the cold-table storm reproduction.
            //
            // ⚠ WHY 200 SEPARATE TYPES AND NOT ONE TYPE HIT 200 TIMES. Same-table concurrency serialises on that
            // store's own `_initLock` (AbstractAsyncStore.cs), so it reproduces nothing — measured on the consumer
            // side, where two earlier hypotheses fired 8 and 12 requests at ONE cold table and found nothing. The
            // condition this file exists to create is ~190 distinct `_initLock`s with no serialisation between them,
            // one shared connector, one file. A store is generic in its entity type and the framework caches table
            // metadata per type, so "distinct cold tables" means distinct CLR types; there is no shorter way to say it.
            //
            // ⚠ WHY FIXED-WIDTH NAMES. `AbstractConnector.CreatedTablesNamedIn` decides whether an escape is the
            // anomaly by testing whether a recorded table name is a SUBSTRING of the statement. Every name here is
            // exactly 8 characters, so no name can be a proper substring of another and that channel cannot
            // contaminate the measurement. The colliding case is measured deliberately and separately.
            // A .g.cs name puts the compiler in auto-generated mode, where a nullable annotation without an
            // explicit directive is CS8669. The project builds warning-free (CLAUDE.md § Code Style), so say it.
            """),

    new(
        RelativePath: Path.Combine("tests", "Birko.Data.SQL.PostgreSQL.Tests", "PgColdTableProbeModels.g.cs"),
        Namespace: "Birko.Data.SQL.PostgreSQL.Tests",
        Prefix: "PgProbe",
        Width: 2,
        Count: 60,
        ClassName: "PgColdTableProbes",
        BlankLineAfterNamespace: true,
        DocComment: null,
        Header: """
            //
            // TASK-296 — distinct entity types for the cold-table storm, ported from the SQLite suite so the same
            // concurrency shape can be pointed at this provider. Fewer than SQLite's 200 on purpose: the question
            // here is whether the CLASS of defect exists at all on a server whose catalogue visibility is
            // transactional and server-side, not to characterise its rate.
            //
            // Fixed-width names, so no name is a proper substring of another and TASK-293's discriminator cannot
            // contaminate the result.
            """),
};

var stale = 0;

foreach (var profile in profiles)
{
    var path = Path.Combine(repoRoot, profile.RelativePath);
    var generated = Render(profile);

    var existing = File.Exists(path) ? File.ReadAllText(path) : null;
    if (existing == generated)
    {
        Report.Say($"= {profile.RelativePath} ({profile.Count} types, unchanged)");
        continue;
    }

    if (checkOnly)
    {
        // A generated file that has drifted from its generator is a file somebody hand-edited despite
        // the "do not hand-edit" line at the top. Name it rather than quietly rewriting it.
        Report.Warn($"! {profile.RelativePath} is STALE — regenerate it");
        stale++;
        continue;
    }

    Directory.CreateDirectory(Path.GetDirectoryName(path)!);
    File.WriteAllText(path, generated);
    Report.Good($"+ {profile.RelativePath} ({profile.Count} types)");
}

if (checkOnly && stale > 0)
{
    Report.Warn($"{stale} generated file(s) do not match the generator.");
    return 1;
}

return 0;

static string Render(Profile profile)
{
    var builder = new StringBuilder();

    // The provenance line names THIS generator. The .ps1 it replaces claimed authorship of a file it
    // could not produce; a header that names the wrong producer is worse than none, because it is read.
    // Repo-relative, not `tools/…`: this generator no longer sits beside the suite it feeds, and it
    // feeds two of them. The path a reader types must work from one place.
    builder.Append("// GENERATED by Birko.Framework/tools/gen-cold-table-probes.cs — do not hand-edit; regenerate instead.\n");
    builder.Append(profile.Header.Replace("\r\n", "\n"));
    builder.Append('\n');
    builder.Append("#nullable enable\n");
    builder.Append('\n');
    builder.Append("using Birko.Data.Models;\n");
    builder.Append("using Birko.Data.SQL.Attributes;\n");
    builder.Append('\n');
    builder.Append($"namespace {profile.Namespace};\n");
    if (profile.BlankLineAfterNamespace) builder.Append('\n');

    for (var i = 0; i < profile.Count; i++)
    {
        var name = profile.Prefix + i.ToString(new string('0', profile.Width));
        builder.Append($"[Table(\"{name}\")] public class {name} : AbstractDatabaseModel {{ public string? Value {{ get; set; }} }}\n");
    }

    builder.Append('\n');
    builder.Append($"public static class {profile.ClassName}\n");
    builder.Append("{\n");
    if (profile.DocComment is not null)
        builder.Append(string.Format(profile.DocComment, profile.Count) + "\n");
    builder.Append("    public static readonly System.Type[] All = new System.Type[]\n");
    builder.Append("    {\n");

    for (var i = 0; i < profile.Count; i++)
        builder.Append($"        typeof({profile.Prefix}{i.ToString(new string('0', profile.Width))}),\n");

    builder.Append("    };\n");
    builder.Append("}\n");

    return builder.ToString();
}

record Profile(
    string RelativePath,
    string Namespace,
    string Prefix,
    int Width,
    int Count,
    string ClassName,
    bool BlankLineAfterNamespace,
    string? DocComment,
    string Header);
