"""Extract compilable C# snippets from the Birko.Framework wiki.

Every ```csharp block on every page is compiled. Two HTML comments steer it, and neither
renders on GitHub:

    <!-- verify:context
    var store = new InMemoryStore<Product>();
    -->

        Page-level setup prepended to every snippet on that page. Most blocks are FRAGMENTS -
        they use `store`, `product` and so on without declaring them, because the surrounding
        prose already introduced them. Without this, a guide written for humans would have to
        be written for the compiler instead.

    <!-- verify:skip reason -->

        Placed immediately before a block that genuinely cannot compile - one that references a
        type the READER is expected to write. The reason is required, so a skip is a decision
        rather than a way to silence the job.

A block may also open with its own `using` directives or declare types. Both are illegal inside
a method body, so they are hoisted: usings to the top of the file, declarations to namespace
scope, and the remaining statements into a method.
"""
import re
import sys
import pathlib

PRELUDE = """// <auto-generated> extracted from the wiki - do not edit </auto-generated>
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using Birko.Data.Models;
using Birko.Data.Stores;
using Birko.Data.SQL.Attributes;
using Birko.Data.SQL.SqLite.Stores;
using Birko.Data.InMemory.Stores;
using Birko.Serialization;
using Birko.Workflow.Definition;
using Birko.Workflow.Execution;
using Birko.BackgroundJobs;
using Birko.BackgroundJobs.Processing;
using Birko.Time;
using Birko.AI.Factories;
using Birko.Communication.REST;
"""

DECL = re.compile(
    r"^\s*(\[[^\]]+\]\s*)*((public|internal|sealed|abstract|static|partial)\s+)*"
    r"(class|record|struct|interface|enum)\s",
    re.M,
)
# a using DIRECTIVE - not `using var x = ...`, which is a legal statement
USING = re.compile(r"^\s*using\s+[A-Za-z_][\w.]*\s*;\s*$")

CONTEXT = re.compile(r"<!--\s*verify:context\s*\n(.*?)-->", re.S)
BLOCK = re.compile(r"(?:(<!--\s*verify:skip[^>]*-->)\s*\n)?```csharp\n(.*?)```", re.S)


TYPENAME = re.compile(
    r"^\s*((public|internal|sealed|abstract|static|partial)\s+)*"
    r"(class|record|struct|interface|enum)\s+([A-Za-z_]\w*)",
    re.M,
)


def drop_shadowed(ctx_decls, snippet_decls):
    """Remove context declarations that the snippet declares itself.

    A page context declares `Product` so the fragments can use it, but the snippet that SHOWS
    the model declares `Product` too. Without this the two collide (CS0101).
    """
    if not ctx_decls or not snippet_decls:
        return ctx_decls
    own = {m.group(4) for m in TYPENAME.finditer(snippet_decls)}
    if not own:
        return ctx_decls
    kept, lines, i = [], ctx_decls.split("\n"), 0
    while i < len(lines):
        m = TYPENAME.match(lines[i])
        if m and m.group(4) in own:
            depth, seen = 0, False
            while i < len(lines):
                depth += lines[i].count("{") - lines[i].count("}")
                if "{" in lines[i]:
                    seen = True
                i += 1
                if seen and depth <= 0:
                    break
            continue
        kept.append(lines[i])
        i += 1
    return "\n".join(kept)


LOCAL = re.compile(r"^\s*(?:var|[\w.<>\[\],\s]+?)\s+([A-Za-z_]\w*)\s*=", re.M)


def drop_shadowed_locals(ctx_stmts, snippet_stmts):
    """Remove context variables that the snippet declares itself.

    The context declares `store` so fragments can use it, but the snippet that SHOWS how to
    build a store declares `store` too. Without this the two collide (CS0128).
    """
    if not ctx_stmts or not snippet_stmts:
        return ctx_stmts
    own = {m.group(1) for m in LOCAL.finditer(snippet_stmts)}
    if not own:
        return ctx_stmts
    kept = []
    for line in ctx_stmts.split("\n"):
        m = LOCAL.match(line)
        if m and m.group(1) in own:
            continue
        kept.append(line)
    return "\n".join(kept)


def split(body):
    """Return (usings, declarations, statements) for one block of C#."""
    lines = body.split("\n")
    usings, decls, stmts = [], [], []
    i = 0
    while i < len(lines):
        j = i
        while j < len(lines) and lines[j].strip().startswith("["):
            j += 1
        if j < len(lines) and DECL.match(lines[j]):
            depth, k, seen = 0, j, False
            while k < len(lines):
                depth += lines[k].count("{") - lines[k].count("}")
                if "{" in lines[k]:
                    seen = True
                k += 1
                if seen and depth <= 0:
                    break
            decls.extend(lines[i:k])
            i = k
            continue
        if USING.match(lines[i]):
            usings.append(lines[i].strip())
            i += 1
            continue
        stmts.append(lines[i])
        i += 1
    return usings, "\n".join(decls), "\n".join(stmts)


def main(wiki_dir, out_dir):
    wiki, out = pathlib.Path(wiki_dir), pathlib.Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    for stale in out.glob("Snippet_*.cs"):
        stale.unlink()

    kept = skipped = 0
    for md in sorted(wiki.glob("*.md")):
        text = md.read_text(encoding="utf-8")

        found = CONTEXT.search(text)
        if found:
            ctx_usings, ctx_decls, ctx_stmts = split(found.group(1).rstrip())
        else:
            ctx_usings, ctx_decls, ctx_stmts = [], "", ""

        for i, m in enumerate(BLOCK.finditer(text)):
            if m.group(1):
                skipped += 1
                continue
            usings, decls, stmts = split(m.group(2).rstrip())
            usings = ctx_usings + [u for u in usings if u not in ctx_usings]
            decls = "\n".join(x for x in (drop_shadowed(ctx_decls, decls), decls) if x)
            stmts = "\n".join(
                x for x in (drop_shadowed_locals(ctx_stmts, stmts), stmts) if x
            )

            name = "Snippet_%s_%d" % (md.stem.replace("-", "_"), i)
            indented = "".join(
                "        " + line + "\n" for line in stmts.split("\n") if line.strip()
            )
            source = (
                PRELUDE
                + "\n".join(usings)
                + "\n\nnamespace WikiSnippets."
                + name
                + ";\n\n"
                + decls
                + "\n\npublic static class Runner\n{\n"
                + "    public static async Task Run()\n    {\n"
                + "        await Task.CompletedTask;\n"
                + indented
                + "    }\n}\n"
            )
            (out / (name + ".cs")).write_text(source, encoding="utf-8")
            kept += 1

    print("extracted %d snippet(s), skipped %d" % (kept, skipped))
    if kept == 0:
        print("::error::no snippets extracted - the wiki layout or fences changed")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1], sys.argv[2]))
