using System;
using Birko.EventBus.Tests.TestResources;
using FluentAssertions;
using Xunit;

namespace Birko.EventBus.Tests
{
    public class EventBaseTests
    {
        [Fact]
        public void EventBase_HasAutoGeneratedId()
        {
            var evt = new OrderPlaced(Guid.NewGuid(), 1m);

            evt.EventGuid.Should().NotBe(Guid.Empty);
        }

        [Fact]
        public void EventBase_HasOccurredAtTimestamp()
        {
            var before = DateTime.UtcNow;
            var evt = new OrderPlaced(Guid.NewGuid(), 1m);
            var after = DateTime.UtcNow;

            evt.OccurredAt.Should().BeOnOrAfter(before).And.BeOnOrBefore(after);
        }

        [Fact]
        public void EventBase_CorrelationIdIsNullByDefault()
        {
            var evt = new OrderPlaced(Guid.NewGuid(), 1m);

            evt.CorrelationGuid.Should().BeNull();
        }

        [Fact]
        public void EventBase_CorrelationIdCanBeSet()
        {
            var correlationId = Guid.NewGuid();
            var evt = new OrderPlaced(Guid.NewGuid(), 1m) { CorrelationGuid = correlationId };

            evt.CorrelationGuid.Should().Be(correlationId);
        }

        [Fact]
        public void EventBase_SourceIsDefined()
        {
            var evt = new OrderPlaced(Guid.NewGuid(), 1m);

            evt.Source.Should().Be("orders");
        }

        [Fact]
        public void EventContext_From_MapsCorrectly()
        {
            var correlationId = Guid.NewGuid();
            var evt = new OrderPlaced(Guid.NewGuid(), 1m) { CorrelationGuid = correlationId };
            var tenantGuid = Guid.NewGuid();

            var ctx = EventContext.From(evt, tenantGuid: tenantGuid, deliveryCount: 3);

            ctx.EventGuid.Should().Be(evt.EventGuid);
            ctx.Source.Should().Be("orders");
            ctx.CorrelationGuid.Should().Be(correlationId);
            ctx.TenantGuid.Should().Be(tenantGuid);
            ctx.DeliveryCount.Should().Be(3);
        }

        [Fact]
        public void TwoEvents_HaveDifferentIds()
        {
            var evt1 = new OrderPlaced(Guid.NewGuid(), 1m);
            var evt2 = new OrderPlaced(Guid.NewGuid(), 2m);

            evt1.EventGuid.Should().NotBe(evt2.EventGuid);
        }
    }
}
